apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox-curl
              image: radial/busyboxplus:curl
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - 'curl -s http://todoapp-service.mateapp.svc.cluster.local:8080/api/health'
          resources:
            requests:
              cpu: '100m'
              memory: '200Mi'
            limits:
              cpu: '100m'
              memory: '400Mi'
          restartPolicy: OnFailure